global:
  scrape_interval: 15s

remote_write:
  - url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
    basic_auth:
      username: 2847633
      password: GRAFANA_PROM_REMOTE_KEY

scrape_configs:
  - job_name: 'hocuspocus-backend'
    static_configs:
      - targets: ['host.docker.internal:4000']
