global:
  scrape_interval: 15s

remote_write:
  - url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
    basic_auth:
      username: 2847633
      password: glc_eyJvIjoiMTYxMDY4MyIsIm4iOiJzdGFjay0xNDYxNzAwLWhtLXdyaXRlLXByb21ldGhldXMtd3JpdGUiLCJrIjoieDEwTFUwZlVobDQwUzNGMzlpdEgyWTNNIiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aC0xIn19

scrape_configs:
  - job_name: 'hocuspocus-backend'
    static_configs:
      - targets: ['host.docker.internal:4000']
